GET http://localhost:4000/get/unread/notification/66d52f22cb333e73b4fa7215
###

POST http://localhost:4000/create/pub
Content-Type: application/json

{
    "name":"วารสาร",
    "confr_id":"ART2023"
}

###

PATCH  http://localhost:4000/update/cate/66b0e3341768dca7f9c5ebdb/null
Content-Type: application/json

{
    "name" : "null"
}

###

DELETE http://localhost:4000/delete/confr/