GET http://localhost:4000/committees-get/6566484708b7bb08b7b97e13

###

POST http://localhost:4000/committees-update/65986d571b61e67f139dff8a
Content-Type: application/json

{
    "topic":["กฏหมาย"]
}