GET http://localhost:4000/host

###

POST http://localhost:4000/create/host
Content-Type: application/json

{
    "fname":"ผู้จัดงาน",
    "lname": "ประชุมนานาชาติ",
    "username":"testhost@mail.com",
    "password":"host1234"
}


###

GET http://localhost:4000/author

###

POST http://localhost:4000/create/author
Content-Type: application/json

{
    "fname":"อาทิตย์",
    "lname": "พิทักษ์ช่วงชู",
    "username":"author@mail.com",
    "password":"author1234"
}


###

###

GET http://localhost:4000/committee

###

POST http://localhost:4000/create/committee
Content-Type: application/json

{
    "fname":"กรรมการ",
    "lname": "งานประชุม",
    "username":"comittee@mail.com",
    "password":"committee1234",
    "add_by":"6566427f6b19fc1bc3122529",
    "confr_code":"ART2023"
}


###

POST http://localhost:4000/create/status
Content-Type: application/json

{
    "status_code":0,
    "name":"รอดำเนินการ"
}


###

GET http://localhost:4000/product

###

GET http://localhost:4000/product/6534de791e507305bb8beed2

###

POST http://localhost:4000/register
Content-Type: application/json

{
    "name":"",
    "email": "testmail.com",
    "password": "123456"
}

###

GET http://localhost:4000/users

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "email" : "testmail.com",
    "password": "123456"
}

###

GET http://localhost:4000/upload/

###
POST http://localhost:4000/get-user/653609c636d33dfe3d0be199
